### ISSUE TITLE
А ты не мог бы сделать конвертёр xls > xlsx в виде exe?

### ISSUE THREAD

**Issue by SilentGopherLnx** [ipetrovanton/OfficeToXml#1]
Привет. Увидел тебя на хабре. К сожалению я не шарю в c# но вопрос конвертации xls > xlsx  для меня неимоверно актуален. Мне приходится читать эксельки созданные не в офисе пользователем, а сгенерированные программами, которые (по моему предположению) нарушают документацию, так как большую часть экселек не переваривают а то и вылетают. Я перерыл множество инструментов в своё время, но пока из самых рабочих вариантов для меня конвертация через 1С, но это ОЧЕНЬ медленно. Вдруг твой вариант будет лучше? Для тебя наверно собрать в exe-файл будет делом 10 минут, который принимает имя файла в виде параметра (или можешь без параметра, просто файл file.xls в папке с exe).
https://github.com/ipetrovanton/OfficeToXml/blob/master/ConverterToXml/Converters/XlsToXlsx.cs

**Comment by SilentGopherLnx** [comment]
вникнул сам. На некоторых эксельках исключения

Unhandled exception. System.IO.IOException: block[ 2 ] already removed
   at NPOI.POIFS.Storage.BlockListImpl.Remove(Int32 index)
   at NPOI.POIFS.Storage.BlockAllocationTableReader.FetchBlocks(Int32 startBlock, Int32 headerPropertiesStartBlock, BlockList blockList)
   at NPOI.POIFS.Storage.BlockListImpl.FetchBlocks(Int32 startBlock, Int32 headerPropertiesStartBlock)
   at NPOI.POIFS.FileSystem.POIFSFileSystem.ProcessProperties(BlockList small_blocks, BlockList big_blocks, IEnumerator properties, DirectoryNode dir, Int32 headerPropertiesStartAt)
   at NPOI.POIFS.FileSystem.POIFSFileSystem..ctor(Stream stream)
   at NPOI.HSSF.UserModel.HSSFWorkbook..ctor(Stream s, Boolean preserveNodes)
   at NPOI.HSSF.UserModel.HSSFWorkbook..ctor(Stream s)
   at ConsoleApp1.XlsToXlsx.Convert(Stream sourceStream) in C:\VisualStudioApps\ConsoleApp1\ConsoleApp1\Program.cs:line 75
   at ConsoleApp1.XlsToXlsx.ConvertToXlsxFile(String xlsPath, String destPath) in C:\VisualStudioApps\ConsoleApp1\ConsoleApp1\Program.cs:line 59
   at ConsoleApp1.Program.Main(String[] args) in C:\VisualStudioApps\ConsoleApp1\ConsoleApp1\Program.cs:line 22
